language: java
jdk: oraclejdk8

install: true
script: ./mvnw clean install

cache:
  directories:
  - $HOME/.m2
  
script:
  - mvn test -B
  
deploy:
  - provider: heroku
  -  api_key: "9a02f373-d95d-43a6-b7ac-6f80609dce7e"